AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Authentication Service - Cognito User Pool

Parameters:
  Environment:
    Type: String 
    Default: dev 
    AllowedValues:
      - dev
      - staging 
      - prod 

Globals:
  Function:
    Runtime: nodejs20.x
    Timeout: 30
    MemorySize: 256
    Environment:
      Variables:
        NODE_ENV: !Ref Environment
        AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1
        COGNITO_USER_POOL_ID: !Ref UserPool
        COGNITO_CLIENT_ID: !Ref UserPoolClient

  Api:
    Cors:
      AllowMethods: "'GET,POST,PUT,DELETE,OPTIONS'"
      AllowHeaders: "'Content-Type,Authorization'"
      AllowOrigin: "'*'"


Resources:
  # ===================================
  # API Gateway
  # ===================================
  AuthApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: !Sub '${Environment}-auth-api'
      StageName: !Ref Environment

  # ===================================
  # Cognito User Pool
  # ===================================
  UserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName:  !Sub '${Environment}-ecommerce-users'
      # Allow users to sign in with email
      UsernameAttributes:
        - email 
      #Auto-verify email addresses 
      AutoVerifiedAttributes:
        - email 
      #Password Policy 
      Policies:
        PasswordPolicy:
          MinimumLength: 8
          RequireUppercase: true 
          RequireLowercase: true 
          RequireNumbers: true 
          RequireSymbols: true 
      # User attributes schema
      Schema:
        - Name: email 
          AttributeDataType: String 
          Required: true 
          Mutable: false 
        - Name: name 
          AttributeDataType: String 
          Required: true 
          Mutable: true 
        - Name: phone_number 
          AttributeDataType: String 
          Required: false 
          Mutable: true 

      # Email configuration
      EmailConfiguration:
        EmailSendingAccount: COGNITO_DEFAULT 

      # Account recovery
      AccountRecoverySetting:
        RecoveryMechanisms:
          - Name: verified_email
            Priority: 1

      # User pool tags 
      UserPoolTags:
        Environment: !Ref Environment
        Service: authentication


  # ===================================
  # Cognito User Pool Client
  # ===================================
  UserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      ClientName: !Sub '${Environment}-ecommerce-web-client'
      UserPoolId: !Ref UserPool

      # Authentication Flows
      ExplicitAuthFlows:
        - ALLOW_USER_PASSWORD_AUTH
        - ALLOW_REFRESH_TOKEN_AUTH
        - ALLOW_USER_SRP_AUTH

      # Token Validity 
      AccessTokenValidity: 1  # 1 hour
      IdTokenValidity: 1      # 1 hour
      RefreshTokenValidity: 30 # 30 days
      TokenValidityUnits:
        AccessToken: hours
        IdToken: hours
        RefreshToken: days

      # Prevent user existence errors
      PreventUserExistenceErrors: ENABLED

      # Read/Write attributes
      ReadAttributes:
        - email 
        - email_verified 
        - name 
        - phone_number 
      WriteAttributes:
        - email 
        - name 
        - phone_number

  # ===================================
  # Cognito User Pool Domain
  # ===================================
  UserPoolDomain:
    Type: AWS::Cognito::UserPoolDomain
    Properties:
      Domain: !Sub '${Environment}-ecommerce-${AWS::AccountId}'
      UserPoolId: !Ref UserPool

  # ===================================
  # Lambda Functions
  # ===================================
  RegisterFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub '${Environment}-auth-register'
      CodeUri: .
      Handler: dist/handlers/register.handler
      Events:
        RegisterApi:
          Type: Api
          Properties:
            RestApiId: !Ref AuthApi
            Path: /auth/register
            Method: POST

  ConfirmRegistrationFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub '${Environment}-auth-confirm'
      CodeUri: .
      Handler: dist/handlers/confirmRegistration.handler
      Events:
        ConfirmApi:
          Type: Api
          Properties:
            RestApiId: !Ref AuthApi
            Path: /auth/confirm
            Method: POST

  LoginFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub '${Environment}-auth-login'
      CodeUri: .
      Handler: dist/handlers/login.handler
      Events:
        LoginApi:
          Type: Api
          Properties:
            RestApiId: !Ref AuthApi
            Path: /auth/login
            Method: POST

  RefreshTokenFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub '${Environment}-auth-refresh'
      CodeUri: .
      Handler: dist/handlers/refreshToken.handler
      Events:
        RefreshApi:
          Type: Api
          Properties:
            RestApiId: !Ref AuthApi
            Path: /auth/refresh
            Method: POST


  LogoutFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub '${Environment}-auth-logout'
      CodeUri: .
      Handler: dist/handlers/logout.handler
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - cognito-idp:GlobalSignOut
              Resource: !GetAtt UserPool.Arn
      Events:
        LogoutApi:
          Type: Api
          Properties:
            RestApiId: !Ref AuthApi
            Path: /auth/logout
            Method: POST


  ForgotPasswordFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub '${Environment}-auth-forgot-password'
      CodeUri: .
      Handler: dist/handlers/forgotPassword.handler
      Events:
        ForgotPasswordApi:
          Type: Api
          Properties:
            RestApiId: !Ref AuthApi
            Path: /auth/forgot-password
            Method: POST

  ResetPasswordFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub '${Environment}-auth-reset-password'
      CodeUri: .
      Handler: dist/handlers/resetPassword.handler
      Events:
        ResetPasswordApi:
          Type: Api
          Properties:
            RestApiId: !Ref AuthApi
            Path: /auth/reset-password
            Method: POST

  ChangePasswordFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub '${Environment}-auth-change-password'
      CodeUri: .
      Handler: dist/handlers/changePassword.handler
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - cognito-idp:ChangePassword
              Resource: !GetAtt UserPool.Arn
      Events:
        ChangePasswordApi:
          Type: Api
          Properties:
            RestApiId: !Ref AuthApi
            Path: /auth/change-password
            Method: POST

    GetProfileFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub '${Environment}-auth-profile'
      CodeUri: .
      Handler: dist/handlers/getProfile.handler
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - cognito-idp:GetUser
              Resource: !GetAtt UserPool.Arn
      Events:
        GetProfileApi:
          Type: Api
          Properties:
            RestApiId: !Ref AuthApi
            Path: /auth/profile
            Method: GET


Outputs:
  AuthApiUrl:
    Description: Auth API Gateway URL
    Value: !Sub 'https://${AuthApi}.execute-api.${AWS::Region}.amazonaws.com/${Environment}'
    Export:
      Name: !Sub '${Environment}-AuthApiUrl'
  UserPoolId:
    Description: Cognito User Pool ID 
    Value: !Ref UserPool 
    Export:
      Name: !Sub '${Environment}-UserPoolId'

  UserPoolArn:
    Description: Cognito User Pool ARN 
    Value: !GetAtt UserPool.Arn
    Export:
      Name: !Sub '${Environment}-UserPoolArn'

  UserPoolClientId:
    Description: Cognito User Pool Client ID 
    Value: !Ref UserPoolClient
    Export:
      Name: !Sub '${Environment}-UserPoolClientId'

  UserPoolDomain:
    Description: Cognito User Pool Domain 
    Value: !Sub '${Environment}-ecommerce-${AWS::AccountId}'

  CognitoLoginUrl:
    Description: Cognito Hosted UI Login URL 
    Value: !Sub 'https://${Environment}-ecommerce-${AWS::AccountId}.auth.${AWS::Region}.amazoncognito.com/login'