export enum ErrorCode {
    //400 Client Errors (Users Mistakes)
    VALIDATION_ERROR = 'VALIDATION_ERROR',
    INVALID_INPUT = 'INVALID_INPUT',
    ORDER_NOT_FOUND = 'ORDER_NOT_FOUND',
    DUPLICATE_ORDER = 'DUPLICATE_ORDER',
    INVALID_STATUS_TRANSITION = 'INVALID_STATUS_TRANSITION',
    CANNOT_CANCEL_SHIPPED_ORDER = 'CANNOT_CANCEL_SHIPPED_ORDER',
    CANNOT_UPDATE_CANCELLED_ORDER = 'CANNOT_UPDATE_CANCELLED_ORDER',
    ORDER_MINIMUM_NOT_MET = 'ORDER_MINIMUM_NOT_MET',
    ORDER_MAXIMUM_EXCEEDED = 'ORDER_MAXIMUM_EXCEEDED',
    TOO_MANY_ITEMS = 'TOO_MANY_ITEMS',
    TOO_FEW_ITEMS = 'TOO_FEW_ITEMS',
    INVALID_ORDER_STATUS = 'INVALID_ORDER_STATUS',
    ITEM_NOT_FOUND_IN_ORDER = 'ITEM_NOT_FOUND_IN_ORDER',
    CANNOT_REMOVE_LAST_ITEM = 'CANNOT_REMOVE_LAST_ITEM',

    //401 - Authentication Errors
    UNAUTHORIZED = 'UNAUTHORIZED',
    TOKEN_EXPIRED = 'TOKEN_EXPIRED',
    INVALID_TOKEN = 'INVALID_TOKEN',
    MISSING_TOKEN = 'MISSING_TOKEN',

    //403 - Authorization Error
    FORBIDDEN = 'FORBIDDEN',
    INSUFFICIENT_PERMISSIONS = 'INSUFFICIENT_PERMISSIONS',
    ACCESS_DENIED = 'ACCESS_DENIED',

    //404 - Not Found
    RESOURCE_NOT_FOUND = 'RESOURCE_NOT_FOUND',

    //409 - Conflit
    CONFLICT = 'CONFLICT',
    ORDER_ALREADY_EXISTS = 'ORDER_ALREADY_EXISTS',

    //429 - Rate Limiting
    RATE_LIMIT_EXCEEDED = 'RATE_LIMIT_EXCEEDED',
    TOO_MANY_REQUESTS = 'TOO_MANY_REQUESTS',

    //500 Server Error
    INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',
    DATABASE_ERROR = 'DATABASE_ERROR',
    DATABASE_TIMEOUT = 'DATABASE_TIMEOUT',
    DATABASE_THROTTLED = 'DATABASE_THROTTLED',
    EXTERNAL_SERVICE_ERROR = 'EXTERNAL_SERVICE_ERROR',
    EVENT_PUBLISH_FAILED = 'EVENT_PUBLISH_FAILED',

    //503 - Service Unavailable
    SERVICE_UNAVAILABLE = 'SERVICE_UNAVAILABLE',
    DATABASE_UNAVAILABLE = 'DATABASE_UNAVAILABLE',
    MAINTENANCE_MODE = 'MAINTENANCE_MODE',
}


export function getHttpStatusForErrorCode(code: ErrorCode): number {
    const statusMap: Record<string, number> = {
    // 400
    [ErrorCode.VALIDATION_ERROR]: 400,
    [ErrorCode.INVALID_INPUT]: 400,
    [ErrorCode.INVALID_STATUS_TRANSITION]: 400,
    [ErrorCode.CANNOT_CANCEL_SHIPPED_ORDER]: 400,
    [ErrorCode.CANNOT_UPDATE_CANCELLED_ORDER]: 400,
    [ErrorCode.ORDER_MINIMUM_NOT_MET]: 400,
    [ErrorCode.ORDER_MAXIMUM_EXCEEDED]: 400,
    [ErrorCode.TOO_MANY_ITEMS]: 400,
    [ErrorCode.TOO_FEW_ITEMS]: 400,
    [ErrorCode.INVALID_ORDER_STATUS]: 400,
    [ErrorCode.ITEM_NOT_FOUND_IN_ORDER]: 400,
    [ErrorCode.CANNOT_REMOVE_LAST_ITEM]: 400,

    // 401
    [ErrorCode.UNAUTHORIZED]: 401,
    [ErrorCode.TOKEN_EXPIRED]: 401,
    [ErrorCode.INVALID_TOKEN]: 401,
    [ErrorCode.MISSING_TOKEN]: 401,

    // 403
    [ErrorCode.FORBIDDEN]: 403,
    [ErrorCode.INSUFFICIENT_PERMISSIONS]: 403,
    [ErrorCode.ACCESS_DENIED]: 403,

    // 404
    [ErrorCode.ORDER_NOT_FOUND]: 404,
    [ErrorCode.RESOURCE_NOT_FOUND]: 404,

    // 409
    [ErrorCode.DUPLICATE_ORDER]: 409,
    [ErrorCode.ORDER_ALREADY_EXISTS]: 409,
    [ErrorCode.CONFLICT]: 409,

    // 429
    [ErrorCode.RATE_LIMIT_EXCEEDED]: 429,
    [ErrorCode.TOO_MANY_REQUESTS]: 429,

    // 500
    [ErrorCode.INTERNAL_SERVER_ERROR]: 500,
    [ErrorCode.DATABASE_ERROR]: 500,
    [ErrorCode.DATABASE_TIMEOUT]: 500,
    [ErrorCode.EXTERNAL_SERVICE_ERROR]: 500,
    [ErrorCode.EVENT_PUBLISH_FAILED]: 500,

    // 503
    [ErrorCode.SERVICE_UNAVAILABLE]: 503,
    [ErrorCode.DATABASE_UNAVAILABLE]: 503,
    [ErrorCode.DATABASE_THROTTLED]: 503,
    [ErrorCode.MAINTENANCE_MODE]: 503,
  };

  return statusMap[code] || 500;
}